### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by eljam** [nexylan/NexySlackBundle#10]
Hi,

I was wondering why did you force to use PHP 5.6 as the library underneath supports php >=5.4 ?

Thanks

**Comment by Soullivaneuh** [comment]
Because it's a new project and as a new project we start from the actual supported PHP version which is 5.6.

See http://php.net/supported-versions.php.

**Comment by eljam** [comment]
Ok it's a little bit harsh as other major bundle still support 5.4 and 5.5 but i understand your choice.
I will try another bundle then.

**Comment by Soullivaneuh** [comment]
We could at least accept PHP 5.5 as it's still supported for Security fixes.

Feel free to send a PR.
